### ISSUE TITLE
What and how to return Occurrence eventDate?

### ISSUE THREAD

**Issue by cgendreau** [gbif/gbif-api#4] opened 2016-09-15 14:12 UTC
**Please see the [comment below](#issuecomment-1385497157) with a proposal for changes.**

The comment below this line is unchanged since 2016.

----

The goal of this issue is to document and collect feedback about the future response of the API related to the date to which an occurrence record occurred. This is strictly related to the response of the API.
## Supported date ISO formats

The following ISO date formats, based on the granularly provided by the data publisher, will be returned by the API:

| Pattern | Example value |
| --- | --- |
| yyyy | 2016 |
| yyyy-mm | 2016-03 |
| yyyy-mm-dd | 2016-03-05 |
| yyyy-mm-dd'T'hh:mm:ss | 2016-03-05T13:03:07 |

Date intervals using the formats above separated with a slash (/): 2016-03-05/2016-03-06.
### Option 1 - Update/reuse the current eventDate

This option consists in reusing the current content of the JSON field `eventDate` returned by the API to return all supported ISO format dates. 
Following this change, the eventDate could contains values like:

```
"eventDate":"2012-03/2012-04"
"eventDate":"2012-03-01/2012-04-02"
"eventDate":"2012-03-01"
"eventDate":"2012-03"
"eventDate":"2016-03-05T13:03:07"
```
### Option 2 - introduce new field(s)

This option consists in adding new field(s) to the JSON response.
For example :

```
"isoEventDate":"2012-03/2012-04"
```

The current eventDate could be one of the following:
- maintained but always empty
- maintained and provided only for non date range
- maintained and always filled (for date ranges it would contains the start of the range)
### What to do with year, month, day

This is an open question for both options.

The different options are:
- remove them to avoid confusion
- maintain them but provide values only for non date range
- maintain them and always return a value(for date ranges it would contains the start of the range)

**Comment by fmendezh** [comment] 2016-09-15 14:19
+1 for Option1

**Comment by sckott** [comment] 2016-09-15 18:58
* I prefer Option1 
* I vote for removing year/month/day fields, i imagine reduces confusion and makes JSON response slightly smaller

**Comment by timrobertson100** [comment] 2016-09-15 19:25
Thanks as always Scott

Can you please comment on your perception of how this will impact existing
tools built on top of rGBIF?

It's manageable to coordinate with you so that rGBIF updates
simultaneously, but anyone who has deployed a workflow using rGBIF who does
not update the rGBIF dependency may suffer.  In doing the update they may
also have to make some edits.

This is the first significant breaking change we're pondering, and it's
difficult to judge if it would have a large impact or be a welcomed
enhancement.

Any thoughts?



On Thu, Sep 15, 2016 at 8:58 PM, Scott Chamberlain <notifications@github.com

**Comment by mdoering** [comment] 2016-09-15 20:00
+1 for Option1 and removal of ymd

**Comment by sckott** [comment] 2016-09-16 05:17
> Can you please comment on your perception of how this will impact existing
tools built on top of rGBIF?

I'd imagine the "tools" built with `rgbif` are likely to be mostly analysis scripts from researchers using GBIF data, but I don't know for sure since it is open source after all. There are some web apps out there built with <http://shiny.rstudio.com/> that may be affected. I can put some feelers out to researchers that use the R client and ask if proposed changes will affect them. 

> It's manageable to coordinate with you so that rGBIF updates
simultaneously, but anyone who has deployed a workflow using rGBIF who does
not update the rGBIF dependency may suffer.  In doing the update they may
also have to make some edits.

Right, and we can't force users to update.  I can add warning messages for users during the transition and add notes to the docs to make it more likely users know about the changes. 

The Python client can be updated at the same time - it's been around less time though so probably not as big of a deal

**Comment by molgor** [comment] 2016-09-16 13:27
Hi!
I vote for option 1 and keep day,month and year fields. Apart from the compatibility issues, mentioned by @sckott , this fields make possible to index by any time on the client side when using a lot of data.

**Comment by cgendreau** [comment] 2016-09-16 13:38
Thanks @molgor 
When the eventDate is a date range, what would you expect in year, month, day fields?

**Comment by kbraak** [comment] 2016-09-16 13:43
Just to add, date ranges are commonly used in sampling event data. 

Knowing the total sampling time allows the quantity of a species recorded in a sample to be calculated per hour, per day, etc.

Here are a few examples of sampling event datasets that use traps operating for many hours or days and thus record the date of the sampling event as a range:

* [Lepidoptera collection of Hannu Saarenmaa](http://www.gbif.org/dataset/84ede380-f762-11e1-a439-00145eb45e9a)
* [Insects from light trap (1992–2009), rooftop Zoological Museum, Copenhagen](http://www.gbif.org/dataset/f506be53-9221-4b44-a41d-5aa0905ec216)
* [Large mammals in Israel from camera traps](http://www.gbif.org/dataset/cdae52c7-a6f2-460e-b0e9-33c795a34224)

**Comment by molgor** [comment] 2016-09-16 14:03
hi @cgendreau !
I'd like the corresponding substring of the field EventDate. with padded zeros ( e.g 08) and full year (yyyy). Perhaps the user could be interested in looking for seasonality presences using month or day ranges and it can easily perform filters based on months instead of parsing the eventdate field previously.

**Comment by cgendreau** [comment] 2016-09-16 14:07
Sorry @molgor I meant when eventDate contains a date ranges like "2012-03-01/2012-04-02".
Would you expect year, month, day to be empty or to contain something like 2012, 3 and 1?

**Comment by molgor** [comment] 2016-09-16 14:20
Sorry @cgendreau, exactly, keep the minimum date.

**Comment by cgendreau** [comment] 2016-09-16 14:45
@kbraak we also already have around 31M record using a date pattern as yyyy-mm-dd/yyyy-mm-dd

**Comment by fmichonneau** [comment] 2016-09-16 14:46
option 1 looks good to me. It might be worth considering adding a field that describes how the date is formatted in eventDate to not have to guess which of the possible combinations is used.

**Comment by sckott** [comment] 2016-09-16 16:37
@fmichonneau but I think it would follow ISO spec, and we can I think simply look for a `/` to see if it's a range, and if so, split on that `/`

**Comment by zachary-foster** [comment] 2016-09-16 17:17
I vote option 1 and no separate year, month, day fields. I am guessing that most people/applications using the api will be able to parse out that information and redundancy is confusing. However, I am a new user of the API, so take my opinion for what it is worth (possibly little).

**Comment by tucotuco** [comment] 2016-09-17 09:37
My response assumes that the original data are always still available in the download if you want them.

Support valid ISO 8601(E) to the fullest extent possible for eventDate, or work to change the definition of Darwin Core's eventDate. Supporting the term as it is defined should obviate the need for the documentation suggested by @fmichonneau.

Construct this eventDate as completely and as unambiguously as possible from the full compliment of event data provided by the data publisher.

Construct the year, month, day as completely and as unambiguously as possible from the full compliment of event data provided by the data publisher. This means that if there is a date range spanning days, day is left blank. If there is a date range spanning months, month is left blank. If there is a date range spanning years, year is left blank.

Construct the startDayOfYear and endDayOfYear as completely and unambiguously as possible from the constructed eventDate. This will facilitate the seasonal interests expressed by @molgor.

By making all of these constructed data consistent, and having access to the original, it should not introduce any of the confusion anticipated by @zachary-foster.

Some Python (sorry Tim) code to demonstrate this approach can be found at:

https://github.com/VertNet/post-harvest-processor/blob/master/lib/vn_utils.py#L368

**Comment by niconoe** [comment] 2016-09-20 08:05
I prefer the simplest possible solution, avoiding confusion and making long-term maintenance easier, therefore **I vote for solution 1, and remove the separate fields**. While I agree it's possible to deduce other fields completely and unambiguously, I think it's unnecessary:  If all the data fit (unambiguously) in 1 standardized field, why make things more complex? 

Other points:

- Using the ISO standard will make it easy for consumers (parsers available for every language around!)
- There are still probably "not too many" API consumers in the wild, so it's still time to make breaking changes, especially if they remove ambiguity and makes the whole system cleaner and easier to maintain.
- Can we use API versioning (there's currently a V1 in the URL) for such changes, keeping the previous version online for a few months? That could at the same time a) let users adapt at their pace b) make GBIF less shy in breaking the API, when needed.
- Of course, all that assumes that the ISO standard work for all cases/existing records.

Hope this helps!

**Comment by niconoe** [comment] 2016-09-20 08:08
BTW, big :thumbsup: to the team for discussing such issues publicly on GitHub!

**Comment by peterdesmet** [comment] 2016-09-23 07:28
1. I would opt for option 1, and removing YMD fields, but I'm also happy to keep the YMD as @tucotuco suggests. It also helps quick lookups.

2. Regarding breaking changes: how is the info **currently** formatted in eventDate? I assume it does currently not contain ranges and that might be the biggest change?

3. For ranges with identical start/end date (2012-03-04/2012-03-04), please return a single date: 2014-03-04

**Comment by dagendresen** [comment] 2017-01-04 13:51
How do we distinguish between eventDate duration and uncertainty?

How do we distinguish if an eventDate such as "1981-01-01/1982-12-01" describe an uncertainty in accuracy of two years, or if the event had an actual duration of two years?

With old museum specimen data the date or even exact year might not be known.

**Comment by zachary-foster** [comment] 2017-01-05 22:49
@dagendresen There could be a combination of the two: and event that lasts a long time but has uncertain start/end dates. 

One solution could be to have another field called "endDate" that is only populated for events with a duration. Then each could be unambiguously uncertain.

Another could be to have different seperators for the two (e.g. "--" for duration and "/" for uncertainty).

**Comment by dagendresen** [comment] 2017-01-06 07:09
Thanks @zachary-foster 
EarliestDateCollected and LatestDateCollected were declared as Darwin Core terms between 2007-04-17 and 2009-04-24, when replaced by eventDate using slash (/) for range.
http://rs.tdwg.org/dwc/terms/history/index.htm#EarliestDateCollected-2007-04-17
http://rs.tdwg.org/dwc/terms/history/index.htm#LatestDateCollected-2007-04-17
http://rs.tdwg.org/dwc/terms/history/index.htm#eventDate-2009-04-24

**Comment by dgasl** [comment] 2017-03-05 18:48
Regarding the question of what to do with year/month/day, perhaps they are redundant for most usages, but I can imagine at least one practical usage of them alone, which I can't figure out how to reproduce using a date or daterange field.

I want to filter my API searches by a certain period of the year, at any year. 
For example, I could be interested in detecting Spanish winter plant occurrences, so I would filter using "month": from december to february

[http://api.gbif.org/v1/occurrence/search?TAXON_KEY=6&COUNTRY=ES&BASIS_OF_RECORD=PRESERVEDSPECIMEN&BASIS_OF_RECORD=PRESERVED_SPECIMEN&MONTH=12%2C*&MONTH=*%2C2](http://api.gbif.org/v1/occurrence/search?TAXON_KEY=6&COUNTRY=ES&BASIS_OF_RECORD=PRESERVEDSPECIMEN&BASIS_OF_RECORD=PRESERVED_SPECIMEN&MONTH=12%2C*&MONTH=*%2C2)

That way I could get data from that period of the year, no matters if these are plants collected last year or two centuries ago. 
Perhaps this can be done in some other way using dates or dateranges, but I don't know how to do it in a single API request (unless event searchable fields support using wild characters for year/day digits).

**Comment by peterdesmet** [comment] 2020-02-11 09:22
As https://github.com/gbif/portal-feedback/issues/652#issuecomment-343407595 suggested to continue discussion on date ranges here. Could the current interpretation of date ranges to single dates by flagged with `DATE_RANGE_IGNORED`?

**Comment by MattBlissett** [comment] 2023-01-17 14:17
# New proposal

(Also for discussion on the mailing list and community forum.)

A longstanding issue with the GBIF API is the interpretation and formatting of the Darwin Core term "eventDate".

**Summary: instead of GBIF changing published `eventDate` values like `2009-03-18/2009-04-13` and `2010` to `2009-03-18` and `2010-01-01` respectively, we propose returning the values `2009-03-18/2009-04-13` and `2010` in the occurrence API and in downloads.  Existing code/scripts that use the `eventDate` value may need to be updated.**

The recommended best practise for the term is "use a date that conforms to ISO 8601-1:2019" (see https://dwc.tdwg.org/terms/#dwc:eventDate).

ISO 8601-1:2019 supports date ranges, and some publishers provide these. Examples are `2000-05`, or `2007-11-13/2007-11-15`.  GBIF's current interpretation changes date ranges like this to the first possible day in the range (`2000-05-01` and `2007-11-13`).

At least 64 million occurrences are affected.

## Change to date interpretation

We propose changing the eventDate field in the GBIF API to support ISO 8601-1 date ranges.  A range will be returned where one was provided by the publisher, either directly as a range in the `eventDate` field, or through a combination of the `year`, `month`, `day`, `startDayOfYear` and `endDayOfYear` fields.

The data quality checks on dates will be improved to check for consistency between these fields: `eventDate`, `year`, `month`, `day`, `startDayOfYear` and `endDayOfYear`.  These fields will only be populated if they are constant for the whole range of dates — a range spanning several days in January 2020 will have `year=2020`, `month=January` and `day=(Blank)`.

`startDayOfYear` and `endDayOfYear` will also be present if the range is accurate to days.

Examples:

| published event date  | intepreted eventDate  | int. year | int. month | int. day | int. sdoy | int. edoy |
|-----------------------|-----------------------|-----------|------------|----------|-----------|-----------|
| 2023-01-13            | 2023-01-13            | 2023      |     1      |  13      |        13 |        13 |
| 2023-01               | 2023-01               | 2023      |     1      |          |           |           |
| 2023                  | 2023                  | 2023      |            |          |           |           |
| 2023-01-13/2023-01-14 | 2023-01-13/2023-01-14 | 2023      |     1      |          |        13 |        14 |
| 2023-01-13/14         | 2023-01-13/14         | 2023      |     1      |          |        13 |        14 |
| 2023-01/2023-02       | 2023-01/2023-02       | 2023      |            |          |           |           |
| 2023-01/02            | 2023-01/02            | 2023      |            |          |           |           |
| 2023/2024             | 2023/2024             |           |            |          |           |           |
| 2023-01-01/2023-12-31 | 2023-01-01/2023-12-31 | 2023      |            |          |         1 |       365 |

Other cases where we can unambigously determine a date or date range will also be handled, for example a record with a `year` and `month` but no `eventDate`, or non-ISO dates like `January 2023`.

### API example:

[This record](https://api.gbif.org/v1/occurrence/1234530937) ([portal link](https://www.gbif.org/occurrence/1234530937)) is published with `eventDate=2009-03-18/2009-04-13`, `year=2009`, `month=3`, `day=18`.  We currently change the `eventDate`:

```json
"year": 2009,
"month": 3,
"day": 18,
"eventDate": "2009-03-18T00:00:00",
```

With this proposal, we would preserve the `eventDate` but remove `day`, as it the event crosses several days:

```json
"year": 2009,
"month": 3,
"eventDate": "2009-03-18/2009-04-13",
```

[This record](https://api.gbif.org/v1/occurrence/2382954724) ([portal link](https://www.gbif.org/occurrence/2382954724)) is published with `eventDate=2019-04-06T20:00:00/2019-04-10T05:00:00` and no separate `day`, `month` or `year` values. Currently, we process it to this:

```json
"year": 2019,
"month": 4,
"day": 6,
"eventDate": "2019-04-06T20:00:00",
```

Instead, we propose returning this:

```json
"year": 2019,
"month": 4,
"eventDate": "2019-04-06T20:00:00/2019-04-10T05:00:00",
"startDayOfYear": 96,
"endDayOfYear": 100,
```

## Searching

The search and download APIs will be affected by this change.

Occurrences will be returned if the occurrence date/date range is **completely within** the query date or date range.

```
Search: eventDate=2023-01-11
Record: eventDate=2023-01-11    -- included
Record: eventDate=2023-01       -- EXCLUDED
Record: eventDate=2023-01-11/12 -- EXCLUDED

Search: eventDate=2023-01-11,2023-01-12
Record: eventDate=2023-01-11    -- included
Record: eventDate=2023-01       -- EXCLUDED
Record: eventDate=2023-01-11/12 -- included

Search: eventDate=*,2023-01 (meaning "Before end of January 2023")
Record: eventDate=2023-01-11    -- included
Record: eventDate=2023-01       -- included
Record: eventDate=2023-01-11/12 -- included

Search: eventDate=2023-01,2023-01 (meaning "After start of January 2023 AND before end of January 2023")
Search: eventDate=2023-01 (same meaning)
Record: eventDate=2023-01-11    -- included
Record: eventDate=2023-01       -- included
Record: eventDate=2023-01-11/12 -- included
```

This implementation will avoid returning occurrences with eventDates like "2010/2021" in many queries. (There are millions of occurrences with large ranges like this.)

## Density maps

There is a year filter for the density/pixel maps.  An occurrence from 2023-01 will be included, but an occurrence with an eventDate spanning more than a single year (like 2022-13-31/2023-01-01) will no longer be included.

## Quarterly analytics, global/regional trends

The quarterly analytics include calculations based on the individual dwc:year, dwc:month and dwc:day fields.  The statistics will be affected where these values change or become blank.

## rGBIF, PyGBIF

Both libraries will be updated as necessary to support eventDate values containing a date range.

## Feedback

We have delayed addressing this issue for a long time, primarily due to concerns about changing the existing behaviour of the API.  However, it's also one of the most frequently requested improvements to GBIF's interpretation.

If you are aware of software or systems which would have problems adapting to the proposed change, please let us know, either here, on the API users mailing list, the community forum or by email to me.

We will alert users in the same places when the change is ready to be tested on the test system at api.gbif-uat.org, where it will be ready for testing for at least 2 weeks.  We will also inform users when the change is to be made live on api.gbif.org.

Thank you,

**Comment by dshorthouse** [comment] 2023-01-19 03:16
What, if anything, might happen to the outputs from this? https://github.com/gbif/occurrence/blob/master/occurrence-hive/src/main/java/org/gbif/occurrence/hive/udf/ToISO8601UDF.java. That's used here https://github.com/gbif/occurrence/blob/master/occurrence-download/src/main/resources/download-workflow/bionomia/hive-scripts/execute-bionomia-query.q#L36 from which I import into a relational db `datetime` field.

**Comment by MattBlissett** [comment] 2023-01-20 15:22
@dshorthouse, I expect ToISO8601UDF to be modified or replaced to support ISO 8601 year-only, year+month-only and ranges.

Since Bionomia has its own download format, we can adjust that format to keep the existing behaviour (take the start of any range, set year/year-month dates to the first of the year/month).  Or, we can output values like `2010`, `2021-05`, `2005-06-08/2005-07-01` and Bionomia can decide how to handle them.

**Comment by MattBlissett** [comment] 2023-09-19 13:33
Note to myself: as well as Bionomia, the Map of Life custom download format will need consideration.

For the moment, I'm retaining the existing behaviour of using the earliest date.

**Comment by MattBlissett** [comment] 2023-09-26 11:50
Hi everyone,

# Event dates — upcoming API change

Early this year we announced a plan to change the way we handle the "eventDate" Darwin Core term.  Date ranges formatted using the ISO 8601 standard, recommended by Darwin Core, will retain their meaning, and the API will return values like "2000-05" or "2007-11-13/2007-11-15", rather than the current behaviour of changing these values to "2000-05-01" and "2007-11-13".

These changes are now visible on GBIF's test system, [GBIF-UAT.org](https://www.gbif-uat.org/).  To allow time for you to test this change against any existing software and scripts you have, we will not implement these changes on [GBIF.org](https://www.gbif.org/) before early November.

## API users

Users of the occurrence API will need to decide how to handle an eventDate like "1880/1889", "1910", "2000-05", "1999-11/2000-03", "2007-11-13/2007-11-15" or "2023-09-22T05:17:10/2023-09-22T12:17:10" — taking the earliest, latest or middle value, randomizing within the range, excluding them etc.  To make parsing easier ranges will always be formatted using the full form and never abbreviated — always "2007-11-13/2007-11-15" and never "2007-11-13/15".

It may be easier to use the individual "year", "month" and "day" fields, which will be present if the year/month/day is constant for the whole range of the eventDate — eventDate=2010-11-25/2010-12-03 will have year=2010, month=NULL, day=NULL as only the year is constant. (However, note a date like 2022-12-31/2023-01-01 covers just 2 days, but as is spans two different years the "year" field will be blank.)

When searching using a range (e.g. eventDate=2005-01,2005-03) only occurrences with eventDates *entirely within* the range will be returned.

## Download users

The "eventDate" column in CSV, Darwin Core and Parquet (cloud snapshot) downloads will contain the same value as in the API, for example "2023-09-22T12:17:10", "2023-09-22", "1880/1889", "1910", "2000-05", "1999-11/2000-03", "2007-11-13/2007-11-15" or "2023-09-22T05:17:10/2023-09-22T12:17:10".

As with the search API, when filtering using a range (e.g. eventDate=2005-01,2005-03) only occurrences with eventDates *entirely within* the range will be returned

## Data interpretation (for data publishers)

Eight Darwin Core terms record information on when an occurrence was collected or observed:

- year
- month
- day
- eventDate
- eventTime
- startDayOfYear
- endDayOfYear
- verbatimEventDate

Some records will have conflicting information in these fields.  Detailed documentation on how we handle the various cases is being prepared, but the general approach is to remove parts of the date that conflict, adding a RECORDED_DATE_MISMATCH issue in this case.  For example, "eventDate=2005-06-01", "year=2005", "month=6" and "day=NULL" would have eventDate changed to "2005-06" and the issue added.

Occurrences published with only one/some fields will have the other fields filled in automatically, where possible. We will not add an issue flag for this.

## Example dataset

A dataset of test occurrences is here: https://www.gbif-uat.org/occurrence/search?dataset_key=d6167827-973d-429a-a00c-8ea294d62d80 providing many examples of consistent and conflicting event date fields. The scientificName is set to a summary of what the eventDate is, and the eventRemarks field has more explanation.

## Feedback

Feedback is welcome on this GitHub issue, or the mailing list or [Discourse forum](https://discourse.gbif.org/t/gbif-api-supporting-ranges-in-occurrence-eventdate/3804).

Thanks,

Matt

**Comment by peterdesmet** [comment] 2023-09-26 12:13
Thanks Matt, reviewing. Some of the `eventRemarks` in the example dataset look [truncated](https://www.gbif-uat.org/occurrence/3090129393) (`"Event date (two days`). Maybe a CSV parsing issue?

**Comment by peterdesmet** [comment] 2023-09-26 13:01
Remarks:

1. [eventDate EDOY conflict](https://www.gbif-uat.org/occurrence/3090129340), [eventDate S+EDOY missing year](https://www.gbif-uat.org/occurrence/3090129367), [YMD EDOY conflict](https://www.gbif-uat.org/occurrence/3090129310): this does test a mismatch between S+EDOY and eventDate, but additionally, these records have a EDOY (12) that is _before_ the SDOY (13). I would test with EDOY of `14`. Additionally a test with SDOY > EDOY might be good.
2. [eventDate EDOY missing year](https://www.gbif-uat.org/occurrence/3090129366), [eventDate S+EDOY missing year](https://www.gbif-uat.org/occurrence/3090129367), [eventDate SDOY missing year](https://www.gbif-uat.org/occurrence/3090129361): why is SDOY or EDOY altered instead of reporting a `Recorded date mismatch`, which is the more conservative approach used in [eventDate SDOY conflict](https://www.gbif-uat.org/occurrence/3090129339) and elsewhere?
3. [eventDate SDOY conflict](https://www.gbif-uat.org/occurrence/3090129398) and [eventDate EDOY conflict](https://www.gbif-uat.org/occurrence/3090129399) contain the same data, which is covered by [eventDate S+EDOY conflict](https://www.gbif-uat.org/occurrence/3090129400). The EDOY and SDOY should be respectively be null for these tests.
4. [eventDateInterval year conflict](https://www.gbif-uat.org/occurrence/3090129364): The `year` falls within the eventDate interval, but it is not interpreted. Why is that? Could more examples be added (unless they are already there) for `month` and `day` that fall within or not within the eventDate range?
5. [Non-ISO DMYY (D=M=Y)](https://www.gbif-uat.org/occurrence/3090129344) has remark `OK but weird`, but it is not interpreted
6. [Non-ISO M-MY](https://www.gbif-uat.org/occurrence/3090129301) has remark `Might be OK`, but it is not interpreted
7. [Non-ISO MDYY (unambig)](https://www.gbif-uat.org/occurrence/3090129345) is unambiguous but is not interpreted. That decision looks fine to me, but might be good to indicate this decision in eventRemarks

Maybe it falls outside the scope of this test, but:

1. How are records interpreted that have conflicting `eventTime` information compared to `eventDate`
2. How are timezones `Z` and `+02:00` interpreted in `eventDate`?

**Comment by MattBlissett** [comment] 2023-09-26 15:26
>  1. [eventDate EDOY conflict](https://www.gbif-uat.org/occurrence/3090129340), [eventDate S+EDOY missing year](https://www.gbif-uat.org/occurrence/3090129367), [YMD EDOY conflict](https://www.gbif-uat.org/occurrence/3090129310): this does test a mismatch between S+EDOY and eventDate, but additionally, these records have a EDOY (12) that is _before_ the SDOY (13). I would test with EDOY of `14`. Additionally a test with SDOY > EDOY might be good.

Thanks, I've changed the tests to use 14 and added an [SDOY > EDOY](https://www.gbif-uat.org/occurrence/3090177306) example.

> 2. [eventDate EDOY missing year](https://www.gbif-uat.org/occurrence/3090129366), [eventDate S+EDOY missing year](https://www.gbif-uat.org/occurrence/3090129367), [eventDate SDOY missing year](https://www.gbif-uat.org/occurrence/3090129361): why is SDOY or EDOY altered instead of reporting a `Recorded date mismatch`, which is the more conservative approach used in [eventDate SDOY conflict](https://www.gbif-uat.org/occurrence/3090129339) and elsewhere?

I agree, the issue should be added, also for the new SDOY > EDOY one.
 
> 3. [eventDate SDOY conflict](https://www.gbif-uat.org/occurrence/3090129398) and [eventDate EDOY conflict](https://www.gbif-uat.org/occurrence/3090129399) contain the same data, which is covered by [eventDate S+EDOY conflict](https://www.gbif-uat.org/occurrence/3090129400). The EDOY and SDOY should be respectively be null for these tests.

Fixed.

> 4. [eventDateInterval year conflict](https://www.gbif-uat.org/occurrence/3090129364): The `year` falls within the eventDate interval, but it is not interpreted. Why is that? Could more examples be added (unless they are already there) for `month` and `day` that fall within or not within the eventDate range?

I've only handled the special case of a year+month+day falling within an eventDate interval, as some people have assigned meaning to this with event datasets.

[eventDateInterval day conflict](https://www.gbif-uat.org/occurrence/3090129349)

[eventDateInterval month conflict](https://www.gbif-uat.org/occurrence/3090129314)

> 5. [Non-ISO DMYY (D=M=Y)](https://www.gbif-uat.org/occurrence/3090129344) has remark `OK but weird`, but it is not interpreted

Remark updated.  The century isn't known for `01/01/01`, so it can't be interpreted.

> 6. [Non-ISO M-MY](https://www.gbif-uat.org/occurrence/3090129301) has remark `Might be OK`, but it is not interpreted

In theory it would be possible to interpret, but we only add non-ISO formats when we notice significant use of the format.  There are only about 1000 occurrences with a date like this.

> 7. [Non-ISO MDYY (unambig)](https://www.gbif-uat.org/occurrence/3090129345) is unambiguous but is not interpreted. That decision looks fine to me, but might be good to indicate this decision in eventRemarks

Updated.

> Maybe it falls outside the scope of this test, but:
> 
> 1. How are records interpreted that have conflicting `eventTime` information compared to `eventDate`

Nothing is done about this, there will be no change from the current behaviour: https://www.gbif.org/occurrence/3089708490 — this particular record seems to have a local (Delaware, -4 hours) timezone in eventDate, and the UTC time in eventTime.

There are 37 million occurrences where eventDate contains a `T` and eventTime is not null, but doesn't exactly match the part after the `T`, and 92 million where it exactly matches.

> 2. How are timezones `Z` and `+02:00` interpreted in `eventDate`?

They are deleted, and the date-time is treated as a local time. This is primarily for the purposes of searching.

**Comment by peterdesmet** [comment] 2023-09-26 16:09
Thanks for updating to `eventDateInterval year conflict ` to  [eventDateInterval year within](https://www.gbif-uat.org/occurrence/3090129364).
- Are you planning to add tests for month within and day within?
- What is the reasoning not to accept YMD values that are _within_ eventDate range?

---

> They are deleted, and the date-time is treated as a local time. This is primarily for the purposes of searching.

This is unfortunate for well provided timestamps for e.g. sensor data (GPS tracking, camera traps, etc.), **especially if they were provided as UTC** (`Z` at end of timestamp). The current implementation removes that they were provided as UTC timestamps and _implies_ a local time (which is incorrect). Would it be possible to find a solution (keeping `Z` in eventDate, adding new field) so that users of the occurrence API and non-verbatim occurrence downloads have that information? Note that I'm not advocating for timezone conversion, just retaining timezone (or maybe restricted to `Z`) information.

**Comment by MattBlissett** [comment] 2023-09-28 09:42
> Are you planning to add tests for month within and day within?

[Month within](https://www.gbif-uat.org/occurrence/3090177301)

[Day within](https://www.gbif-uat.org/occurrence/3090129347) — the difference is I'm not adding an issue for this case.

> What is the reasoning not to accept YMD values that are _within_ eventDate range?

It's not clear what is meant by an eventDate being a range and day being a day within that range.  The TDWG Data Quality group considers this non-compliant use of DWC: https://github.com/tdwg/bdq/issues/67#issuecomment-1605232576

----

> > They are deleted, and the date-time is treated as a local time. This is primarily for the purposes of searching.
> 
> This is unfortunate for well provided timestamps for e.g. sensor data (GPS tracking, camera traps, etc.), **especially if they were provided as UTC** (`Z` at end of timestamp). The current implementation removes that they were provided as UTC timestamps and _implies_ a local time (which is incorrect). Would it be possible to find a solution (keeping `Z` in eventDate, adding new field) so that users of the occurrence API and non-verbatim occurrence downloads have that information? Note that I'm not advocating for timezone conversion, just retaining timezone (or maybe restricted to `Z`) information.

Keeping `Z` where it's provided is a good suggestion. Let's also see if anyone else is interested in that.

**Comment by MattBlissett** [comment] 2024-01-25 12:26
> Keeping `Z` where it's provided is a good suggestion. Let's also see if anyone else is interested in that.

This was implemented.

This should be visible on gbif.org tomorrow.  There's also documentation on the new technical documentation site, https://techdocs.gbif.org/en/data-processing/temporal-interpretation

**Closed by MattBlissett** 2024-01-25 12:26 UTC
